import Head from "next/head";
import React, { useState } from "react";
import { Accordion } from "@/components/Accordion";
import Link from "next/link";

export default function Home() {
  const [items, setItems] = useState([
    {
      heading: "Writing well for the web",
      content: "This is the content for Writing well for the web.",
      expanded: true,
    },
    {
      heading: "Writing well for specialists",
      content: "This is the content for Writing well for specialists.",
    },
  ]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="govuk-width-container ">
        <main className="govuk-main-wrapper " id="main-content" role="main">
          <h1 className="govuk-heading-xl">Default page template</h1>
          <p className="govuk-body">
            <Link className="govuk-link" href="/page2">Page 2</Link>
          </p>
          <button
            style={{ marginBottom: "1rem" }}
            onClick={() =>
              setItems((current) => [
                ...current,
                {
                  heading: "New section",
                  content: "This is the content for New section.",
                },
              ])
            }
          >
            Add section to accordion
          </button>
          <Accordion items={items} />
        </main>
      </div>
    </>
  );
}
